version: 2

updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "manual"
    open-pull-requests-limit: 30

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "manual"
